<h1><?php echo $this->title; ?></h1>
<a href="<?php echo $this->baseUrl('options/addvalue/profile_option_id/' . $this->profile_option_id); ?>"><?php echo $this->translate('Add value'); ?></a>
<table cellpadding="0" cellspacing="1" style="width: 100%; text-align: left;" id="contests">
	<tr>
		<th>
			<?php echo $this->translate('Value'); ?>
		</th>
		<th>
			<?php echo $this->translate('Sort order'); ?>
		</th>
		<th></th>
	</tr
	<?php foreach($this->values as $data) { ?>
		<tr>
			<td>
				<?php echo $data['name']; ?>
			</td>
			<td><?php echo $data['sort_order']; ?></td>
			<td>
				<a href="<?php echo $this->baseUrl('options/editvalue/profile_option_value_id/' . $data['profile_option_value_id']); ?>"><?php echo $this->translate('Edit'); ?></a> | 
				<a onclick="if(confirm('<?php echo $this->translate('Do you really want to delete the value?'); ?>')) location = '<?php echo $this->baseUrl('options/removevalue/profile_option_value_id/' . $data['profile_option_value_id']); ?>';"><?php echo $this->translate('Remove'); ?></a>
			</td>
		</tr>
	<?php } ?>
</table>
