<?php if ($this->pageCount > 1): ?>
<div id="navigation">


<?php if (isset($this->previous)): ?>
  <a class="navigation" href="<?php echo $this->url(array('page' => $this->previous)); ?>">
    < <?php echo $this->translate('Back'); ?>
  </a> |
<?php else: ?>
  <a class="navigation">
    < <?php echo $this->translate('Back'); ?>
  </a> |
<?php endif; ?>
 


<?php if (isset($this->next)): ?>
  <a class="navigation back" href="<?php echo $this->url(array('page' => $this->next)); ?>">
    <?php echo $this->translate('Next'); ?> >
  </a>
<?php else: ?>
  <a class="navigation back">
    <?php echo $this->translate('Next'); ?> >
  </a>
<?php endif; ?>



<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a class="page" href="<?php echo $this->url(array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a>
  <?php else: ?>
    <a class="pages">
        <?php echo $page; ?>
    </a>
  <?php endif; ?>
<?php endforeach; ?>
 
</div>
<?php endif; ?>

