<?php if(!$this->user) { ?>
<!-- Registration PopUp Form for Gentlemens -->
    <div class="popUpW popUpRegF popUpRegFG">
    	<!-- Close Button -->
    	<a href="javascript:void(0);" title="Close Window" class="popUpCloseBtn"></a>
        <!-- END Close Button -->
        
        <h1><?php echo $this->translate('Registration for Gentlemen'); ?></h1>
		<!-- Registration Form -->
        <div class="regF uniformF"></div>
    	<!-- END Registration Form -->
    </div>
    <!-- END Registration PopUp Form for Gentlemens -->
<?php } ?>