<h1><?php echo $this->translate('Chats for user') . ' ' . $this->current_user['fullname']; ?></h1>
<table cellpadding="0" cellspacing="1" style="width: 100%; text-align: left;" id="contests">
	<tr>
		<th><?php echo $this->translate('User'); ?></th>

		<th></th>
	</tr>
	<?php foreach($this->chats as $data) { ?>
		<?php if($data['user_id']) { ?>
		<tr>
			<td>
				<a href="<?php echo $this->baseUrl('users/edit/user_id/') . $data['user_id']; ?>"><?php echo $data['fullname']; ?></a>
			</td>

			<td style="text-align: right;">
				<a href="<?php echo $this->baseUrl('chat/watch/user_1/') . $this->current_user['user_id'] . '/user_2/' . $data['user_id']; ?>"><?php echo $this->translate('Edit chat'); ?></a>
			</td>
		</tr>
		<?php } ?>
	<?php } ?>
</table>

