<table cellpadding="0" cellspacing="1" style="width: 50%; text-align: left;" id="contests">
<tr>
	<th><?php echo $this->translate('User'); ?></th>
	<th><?php echo $this->translate('Message'); ?></th>
	<th></th>
	<th></th>
</tr>
<?php foreach($this->chat as $message) { ?>
<tr>
	<?php if($message['from_user_id'] == $this->user_1['user_id']) { ?>
		<td><?php echo $this->user_1['fullname'] . ' (' . $message['date_added'] . ')'; ?></td>
	<?php }else { ?>
		<td><?php echo $this->user_2['fullname'] . ' (' . $message['date_added'] . ')'; ?></td>
	<?php } ?>
	<td><?php echo $message['description']; ?></td>
	<td><a href="<?php echo $this->baseUrl('chat/editmessage/message_id/') . $message['message_id'] . '?redirect=/chat/watch/user_1/' . $this->user_1['user_id'] . '/user_2/' . $this->user_2['user_id']; ?>"><?php echo $this->translate('Edit'); ?></a></td>
	<td><a href="<?php echo $this->baseUrl('chat/removemessage/message_id/') . $message['message_id'] . '?redirect=/chat/watch/user_1/' . $this->user_1['user_id'] . '/user_2/' . $this->user_2['user_id']; ?>"><?php echo $this->translate('Remove'); ?></a></td>
</tr>
<?php } ?>
</table>