<div class="content">
            	<?php echo $this->action('menu', 'widgets'); ?>
                
                <div class="clear"></div>
                
                <!-- Left Column -->
                <div class="left">
                
                    <?php echo $this->action('accountmenu', 'widgets'); ?>
                    
                    <?php echo $this->action('notification', 'widgets'); ?>
                </div>
                <!-- END Left Column -->
                
                <!-- Right Column -->
                <div class="right">
                	<h1><?php echo $this->translate('My friends'); ?></h1>
                	
                	
					
					<?php foreach($this->friends as $friend) { ?>
						<div class="request-image">
							<a href="<?php echo $this->baseUrl('user/') . $friend['user_id']; ?>"><img src="<?php echo Site_Image::resize($friend['image'], 100, 100); ?>" alt="" /></a>
							<a href="<?php echo $this->baseUrl('user/') . $friend['user_id']; ?>"><?php echo $friend['fullname']; ?></a>
							<div class="buttons_a">
								<div class="button"><a href="<?php echo $this->baseUrl('chat/chat/user/') . $friend['user_id']; ?>"><?php echo $this->translate('Write'); ?></a></div>
							</div>
							<div style="clear: both;"></div>
						</div>
					<?php } ?>
                </div>
                <!-- END Right Column -->
                
                
                <div class="clear"></div>
            </div>