<div class="content">
                <div class="steps">
                    <div class="stepHeart">1</div>
                    <div class="stepHeart">2</div>
                    <div class="stepWBear"></div>
                    <div class="stepPanda"></div>
                </div>
                <div class="clear"></div>
                
                <h1><?php echo $this->title; ?></h1>
                
            	<!-- Profile Form -->
                <div class="profileF uniformF">
                    <?php echo $this->form; ?>
                </div>
                <!-- END Profile Form -->
            </div>